apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  labels: 
    app: landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: gcr.io/just-student-344815/landing:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 512Mi
            cpu: 250m
          limits:
            memory: 1024Mi
            cpu: 500m
